version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: billpush_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: billpush
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: billpush_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    external: true
    name: 04bdbfb1291efc445406c265bbc0f870571989d7f4125975fe4bf8504eb64dfc
  redis_data:
